//THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY MGEN. DO NOT MODIFY BY HAND

/**
* Copyright (c) 2007 Ian Rae
* All Rights Reserved.
* Licensed under the Eclipse Public License - v 1.0
* For more information see http://www.eclipse.org/legal/epl-v10.html
*/
package org.speakright.demos.simpsons;
import org.speakright.core.*;
import java.io.Serializable;

@SuppressWarnings("serial")
public class Model implements IModel {
	
	transient private IModelBinder m_binder;
	public IModelBinder ModelBinder() 
	{
		return m_binder;
	}
	public void ModelBinderSet(IModelBinder binder)
	{
		m_binder = binder;
	}
	
	//mvn -- model variable names
	public MVN ModelVarNames = new MVN();
	@SuppressWarnings("serial")
	class MVN implements Serializable
	{
				public final String NEXTACTION = "nextAction";
				public final String CURRENTCHARACTERID = "currentCharacterId";
				public final String CHARACTERNAME = "characterName";
				public final String HAVEVOTED = "haveVoted";
	}
	
	//raw additions
	public SimpsonsData m_simpsons = new SimpsonsData();  /*raw*/
	public Voting m_voting; //needs to be injected at runtime   /*raw*/

	//values
		protected StringItem m_nextAction = new StringItem(ModelVarNames.NEXTACTION);
		public StringItem nextAction() 
		{
			return m_nextAction;
		}
		protected IntItem m_currentCharacterId = new IntItem(ModelVarNames.CURRENTCHARACTERID);
		public IntItem currentCharacterId() 
		{
			return m_currentCharacterId;
		}
		protected StringItem m_characterName = new StringItem(ModelVarNames.CHARACTERNAME);
		public StringItem characterName() 
		{
			return m_characterName;
		}
		protected BooleanItem m_haveVoted = new BooleanItem(ModelVarNames.HAVEVOTED);
		public BooleanItem haveVoted() 
		{
			return m_haveVoted;
		}
	
	//******** ITEM CLASSES*************
		static public class StringItem extends ModelItemBase implements Serializable {
			String m_value;
			StringItem(String name, String val) 
			{ 
				m_name = name;
				m_value = val; 
				logValueChange();
			}
			void logValueChange()
			{
				log(m_name + " = " + m_value);				
			}
			StringItem(String name) 
			{
				m_name = name; 
				m_value = ""; 
				logValueChange();
			}
			
			public Object rawValue()
			{
				return m_value;
			}
			
			public void clear()
			{
				m_value = "";
				m_isSet = false;
				logValueChange();
			}
			
			public String get() { return m_value; }
			
			public void set(String val) 
			{
				m_isSet = true;
				m_value = val; 
				logValueChange();
			}
		}
		static public class IntItem extends ModelItemBase implements Serializable {
			int m_value;
			IntItem(String name, int val) 
			{ 
				m_name = name;
				m_value = val; 
				logValueChange();
			}
			void logValueChange()
			{
				log(m_name + " = " + m_value);				
			}
			IntItem(String name) 
			{
				m_name = name; 
				m_value = 0; 
				logValueChange();
			}
			
			public Object rawValue()
			{
				return m_value;
			}
			
			public void clear()
			{
				m_value = 0;
				m_isSet = false;
				logValueChange();
			}
			
			public int get() { return m_value; }
			
			public void set(int val) 
			{
				m_isSet = true;
				m_value = val; 
				logValueChange();
			}
		}
		static public class BooleanItem extends ModelItemBase implements Serializable {
			boolean m_value;
			BooleanItem(String name, boolean val) 
			{ 
				m_name = name;
				m_value = val; 
				logValueChange();
			}
			void logValueChange()
			{
				log(m_name + " = " + m_value);				
			}
			BooleanItem(String name) 
			{
				m_name = name; 
				m_value = false; 
				logValueChange();
			}
			
			public Object rawValue()
			{
				return m_value;
			}
			
			public void clear()
			{
				m_value = false;
				m_isSet = false;
				logValueChange();
			}
			
			public boolean get() { return m_value; }
			
			public void set(boolean val) 
			{
				m_isSet = true;
				m_value = val; 
				logValueChange();
			}
		}
}

