//THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY MGEN. DO NOT MODIFY BY HAND

package org.speakright.core.tests;
import org.speakright.core.*;
import java.io.Serializable;

@SuppressWarnings("serial")
public class Model implements IModel {
	
	transient private IModelBinder m_binder;
	public IModelBinder ModelBinder() 
	{
		return m_binder;
	}
	public void ModelBinderSet(IModelBinder binder)
	{
		m_binder = binder;
	}
	
	//mvn -- model variable names
	public MVN ModelVarNames = new MVN();
	@SuppressWarnings("serial")
	class MVN implements Serializable
	{
				public final String CITY = "city";
				public final String X = "x";
				public final String LOGGEDIN = "loggedIn";
				public final String HACK = "hack";
	}
	

	//values
		protected StringItem m_city = new StringItem();
		public StringItem city() 
		{
			return m_city;
		}
		protected IntItem m_x = new IntItem();
		public IntItem x() 
		{
			return m_x;
		}
		protected BooleanItem m_loggedIn = new BooleanItem();
		public BooleanItem loggedIn() 
		{
			return m_loggedIn;
		}
		protected StringItem m_hack = new StringItem();
		public StringItem hack() 
		{
			return m_hack;
		}
	
	//******** ITEM CLASSES*************
		static public class StringItem extends ModelItemBase implements Serializable {
			String m_value;
			StringItem(String val) { m_value = val; }
			StringItem() { m_value = ""; }
			
			public Object rawValue()
			{
				return m_value;
			}
			
			public void clear()
			{
				m_value = "";
				m_isSet = false;
			}
			
			public String get() { return m_value; }
			
			public void set(String val) 
			{
				m_isSet = true;
				m_value = val; 
			}
		}
		static public class IntItem extends ModelItemBase implements Serializable {
			int m_value;
			IntItem(int val) { m_value = val; }
			IntItem() { m_value = 0; }
			
			public Object rawValue()
			{
				return m_value;
			}
			
			public void clear()
			{
				m_value = 0;
				m_isSet = false;
			}
			
			public int get() { return m_value; }
			
			public void set(int val) 
			{
				m_isSet = true;
				m_value = val; 
			}
		}
		static public class BooleanItem extends ModelItemBase implements Serializable {
			boolean m_value;
			BooleanItem(boolean val) { m_value = val; }
			BooleanItem() { m_value = false; }
			
			public Object rawValue()
			{
				return m_value;
			}
			
			public void clear()
			{
				m_value = false;
				m_isSet = false;
			}
			
			public boolean get() { return m_value; }
			
			public void set(boolean val) 
			{
				m_isSet = true;
				m_value = val; 
			}
		}
}

