/**
* Copyright (c) 2007 Ian Rae
* All Rights Reserved.
* Licensed under the Eclipse Public License - v 1.0
* For more information see http://www.eclipse.org/legal/epl-v10.html
*/
package org.speakright.core;

/**
 * Base class for most IModel classes.  Implements
 * the model binder API.
 * 
 * The class generated by MGen uses this class.
 * @author IanRaeLaptop
 *
 */
@SuppressWarnings("serial")
public class ModelBase implements IModel {

	transient IModelBinder m_binder;
	public IModelBinder ModelBinder() {
		return m_binder;
	}

	public void ModelBinderSet(IModelBinder binder) {
		m_binder = binder;
	}
}
